# Generated by Django 5.2 on 2025-04-16 12:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Files",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="updated at"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="primary key",
                    ),
                ),
                ("url", models.URLField(max_length=300)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("type", models.CharField(blank=True, max_length=100)),
                ("size", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "file",
                "verbose_name_plural": "files",
                "db_table": "file",
                "ordering": ["-created_at"],
            },
        ),
    ]
