# Generated by Django 6.1 on 2026-09-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, verbose_name="bio"),
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                default="en", max_length=35, verbose_name="language"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="public_profile",
            field=models.BooleanField(default=False, verbose_name="public profile"),
        ),
        migrations.AddField(
            model_name="user",
            name="search_engine_visibility",
            field=models.BooleanField(
                default=False, verbose_name="search engine visibility"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="share_learning_activity",
            field=models.BooleanField(
                default=False, verbose_name="share learning activity"
            ),
        ),
    ]
