# Generated by Django 6.1 on 2026-09-23 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Localization",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="updated at"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="primary key",
                    ),
                ),
                ("language_name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
