# Generated by Django 6.1 on 2026-09-24 18:19

import cloudinary_storage.storage
import cloudinary_storage.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('section', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='primary key')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('rejected', 'Rejected')], default='draft', max_length=10)),
                ('lecture_type', models.CharField(choices=[('video', 'Video'), ('document', 'Document')], default='video', max_length=10)),
                ('source', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='lecture/', validators=[cloudinary_storage.validators.validate_video])),
                ('is_preview', models.BooleanField(default=False)),
                ('document_content', models.TextField(blank=True, null=True)),
                ('reject_reason', models.TextField(null=True)),
                ('resources', models.JSONField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(null=True, upload_to='lecture/')),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lecture', to='course.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lecture', to='section.section')),
            ],
            options={
                'verbose_name': 'lecture',
                'verbose_name_plural': 'lectures',
                'db_table': 'lecture',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
