# Generated by Django 6.1 on 2026-09-25 16:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="updated at"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="primary key",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("is_global", models.BooleanField(default=False)),
                ("is_unlimited", models.BooleanField(default=False)),
                ("is_instructor_created", models.BooleanField(default=True)),
                ("limit", models.IntegerField(default=10)),
                ("value", models.IntegerField(default=10)),
                ("used", models.IntegerField(default=0)),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("fixed", "Fixed")],
                        default="percentage",
                        max_length=15,
                    ),
                ),
                ("expired_at", models.DateField(default=None, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="course.course"
                    ),
                ),
            ],
            options={
                "verbose_name": "coupon",
                "verbose_name_plural": "coupons",
                "db_table": "coupon",
                "ordering": ["-created_at"],
            },
        ),
    ]
